/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sociotorcedor.view;

import com.sociotorcedor.controller.PagamentoController;
import com.sociotorcedor.model.Pagamento;
import com.sociotorcedor.model.Torcedor;
import com.sociotorcedor.model.Plano;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PagamentoView extends javax.swing.JFrame {
    
    private final PagamentoController controller;
    private int idPagamentoSelecionado = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PagamentoView.class.getName());

    public PagamentoView() {
        initComponents();
        this.controller = new PagamentoController();

        this.controller.getPagamentosObservaveis().sign(
            listaDePagamentos -> atualizarTabela(listaDePagamentos)
        );
        
        carregarTorcedoresNoComboBox();
        this.controller.getPagamentosObservaveis().ping();
    }
    
    private void carregarTorcedoresNoComboBox() {
        List<Torcedor> torcedores = controller.listarTodosTorcedores();
        DefaultComboBoxModel<Torcedor> model = new DefaultComboBoxModel<>();

        for (Torcedor t : torcedores) {
            model.addElement(t);
        }
        comboTorcedores.setModel(model);
        comboTorcedores.setSelectedIndex(-1); // Garante que nada esteja selecionado no início
    }

    private void atualizarTabela(List<Pagamento> pagamentos) {
        DefaultTableModel model = (DefaultTableModel) tabelaPagamento.getModel();
        model.setRowCount(0);

        for (Pagamento p : pagamentos) {
            model.addRow(new Object[]{
                p.getId(),
                p.getTorcedor() != null ? p.getTorcedor().getNome() : "Torcedor não encontrado",
                p.getDataPagamento(),
                p.getValorPago(),
                p.getMetodoPagamento()
            });
        }
    }
    
    private void limparCampos() {
        comboTorcedores.setSelectedIndex(-1);
        campoDataPagamento.setText("");
        campoValorPago.setText("");
        campoMetodoPagamento.setSelectedIndex(0);
        idPagamentoSelecionado = -1;
        tabelaPagamento.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTorcedores = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        labelPagamento = new javax.swing.JLabel();
        comboTorcedores = new javax.swing.JComboBox<>();
        campoDataPagamento = new javax.swing.JTextField();
        campoValorPago = new javax.swing.JTextField();
        campoMetodoPagamento = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPagamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 238, 239));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Novo Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 12))); // NOI18N

        labelTorcedores.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelTorcedores.setText("Sócio Torcedor:");
        labelTorcedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(207, 238, 239), new java.awt.Color(207, 238, 239), java.awt.Color.white, java.awt.Color.white));

        labelData.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelData.setText("Data do Pagamento:");
        labelData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(207, 238, 239), new java.awt.Color(207, 238, 239), java.awt.Color.white, java.awt.Color.white));

        labelValor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelValor.setText("Valor Pago(R$):");
        labelValor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(207, 238, 239), new java.awt.Color(207, 238, 239), java.awt.Color.white, java.awt.Color.white));

        labelPagamento.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelPagamento.setText("Método de Pagamento:");
        labelPagamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(207, 238, 239), new java.awt.Color(207, 238, 239), java.awt.Color.white, java.awt.Color.white));

        comboTorcedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTorcedoresActionPerformed(evt);
            }
        });

        campoDataPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataPagamentoActionPerformed(evt);
            }
        });

        campoMetodoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIX", "Cartão de Crédito", "Cartão de Débito", "Dinheiro" }));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnRegistrar.setText("Registrar pagamento");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoMetodoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)
                        .addGap(40, 40, 40)
                        .addComponent(btnExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTorcedores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTorcedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelData, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTorcedores)
                    .addComponent(comboTorcedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelData)
                    .addComponent(campoDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValor)
                    .addComponent(campoValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPagamento)
                    .addComponent(campoMetodoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnExcluir))
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(207, 238, 239));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabelaPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Torcedor", "Data Pag.", "Valor pago", "Método"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPagamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaPagamento);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoDataPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataPagamentoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         try {
            Torcedor torcedorSelecionado = (Torcedor) comboTorcedores.getSelectedItem();
            String data = campoDataPagamento.getText().trim();
            double valor = Double.parseDouble(campoValorPago.getText().trim().replace(",", "."));
            String metodo = (String) campoMetodoPagamento.getSelectedItem();
            
            controller.registrarPagamento(torcedorSelecionado, data, valor, metodo);
            
            JOptionPane.showMessageDialog(this, "Pagamento registrado com sucesso!");
            limparCampos();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: O campo 'Valor' deve ser um número válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Erro de Validação: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (idPagamentoSelecionado == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um pagamento na tabela para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este registro de pagamento?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if (resposta == JOptionPane.YES_OPTION) {
            controller.excluir(idPagamentoSelecionado);
            limparCampos();
            JOptionPane.showMessageDialog(this, "Pagamento excluído com sucesso.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tabelaPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPagamentoMouseClicked
        int linha = tabelaPagamento.getSelectedRow();
        if (linha != -1) {
            idPagamentoSelecionado = Integer.parseInt(String.valueOf(tabelaPagamento.getValueAt(linha, 0)));
        }
    }//GEN-LAST:event_tabelaPagamentoMouseClicked

    private void comboTorcedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTorcedoresActionPerformed
        Torcedor torcedorSelecionado = (Torcedor) comboTorcedores.getSelectedItem();
        if (torcedorSelecionado != null) {
            Plano planoDoTorcedor = torcedorSelecionado.getPlano();
            if (planoDoTorcedor != null) {
                double valorDoPlano = planoDoTorcedor.getValor();      
                campoValorPago.setText(String.valueOf(valorDoPlano));
            }
        } else {
            campoValorPago.setText("");
        }
    }//GEN-LAST:event_comboTorcedoresActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PagamentoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField campoDataPagamento;
    private javax.swing.JComboBox<String> campoMetodoPagamento;
    private javax.swing.JTextField campoValorPago;
    private javax.swing.JComboBox<Torcedor> comboTorcedores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelPagamento;
    private javax.swing.JLabel labelTorcedores;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTable tabelaPagamento;
    // End of variables declaration//GEN-END:variables
}
