/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sociotorcedor.view;

import com.sociotorcedor.controller.TorcedorController;
import com.sociotorcedor.model.Plano;
import com.sociotorcedor.model.Torcedor;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class TorcedorView extends javax.swing.JFrame {
    
    private final TorcedorController controller;
    private int idTorcedorSelecionado = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TorcedorView.class.getName());

    /**
     * Creates new form TorcedorView
     */
    public TorcedorView() {
        initComponents();
        this.controller = new TorcedorController();

        this.controller.getTorcedoresObservaveis().sign(
            listaDeTorcedores -> atualizarTabelaTorcedores(listaDeTorcedores)
        );
        
        carregarPlanosNoComboBox();
        this.controller.getTorcedoresObservaveis().ping();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTorcedor = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoNomeTorcedor = new javax.swing.JTextField();
        labelPlanos = new javax.swing.JLabel();
        comboPlanos = new javax.swing.JComboBox<>();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTorcedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(207, 238, 239));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Sócio Torcedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 12))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(423, 372));

        labelTorcedor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelTorcedor.setText("Nome Completo:");
        labelTorcedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(207, 238, 239), new java.awt.Color(207, 238, 239), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));

        labelCPF.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelCPF.setText("CPF:");
        labelCPF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(207, 238, 239), new java.awt.Color(207, 238, 239), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));

        labelEmail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelEmail.setText("Email:");
        labelEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(207, 238, 239), new java.awt.Color(207, 238, 239), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));

        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });

        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });

        labelPlanos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelPlanos.setText("Plano:");
        labelPlanos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(207, 238, 239), new java.awt.Color(207, 238, 239), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));

        btnNovo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(39, 39, 39)
                        .addComponent(btnSalvar)
                        .addGap(34, 34, 34)
                        .addComponent(btnExcluir)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelPlanos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPlanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTorcedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNomeTorcedor, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTorcedor)
                    .addComponent(campoNomeTorcedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlanos)
                    .addComponent(comboPlanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir))
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(207, 238, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setToolTipText("");

        tabelaTorcedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Email", "Plano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaTorcedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTorcedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaTorcedores);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        // responsável por buscar os planos e preencher a caixa de seleção.
    private void carregarPlanosNoComboBox() {
        List<Plano> planos = controller.listarTodosPlanos();
        DefaultComboBoxModel<Plano> model = new DefaultComboBoxModel<>();
        for (Plano p : planos) {
            model.addElement(p);
        }
        comboPlanos.setModel(model);
    }

    // carregar/atualizar os dados na tabela de torcedores
    public void atualizarTabelaTorcedores(List<Torcedor> torcedores) {
        DefaultTableModel model = (DefaultTableModel) tabelaTorcedores.getModel();
        model.setRowCount(0);

        for (Torcedor t : torcedores) {
            model.addRow(new Object[]{
                t.getId(),
                t.getNome(),
                t.getCpf(),
                t.getEmail(),
                t.getPlano() != null ? t.getPlano().getNome() : ""
            });
        }
    }
    // Limpa os campos do formulário e reseta o ID selecionado.
    private void limparCampos() {
        campoNomeTorcedor.setText("");
        campoCpf.setText("");
        campoEmail.setText("");
        comboPlanos.setSelectedIndex(-1); // Desseleciona qualquer plano
        idTorcedorSelecionado = -1;
        tabelaTorcedores.clearSelection();
    }
    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        
    }//GEN-LAST:event_campoCpfActionPerformed

    
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            String nome = campoNomeTorcedor.getText().trim();
            String cpf = campoCpf.getText().trim();
            String email = campoEmail.getText().trim();
            Plano planoSelecionado = (Plano) comboPlanos.getSelectedItem();

            if (idTorcedorSelecionado == -1) { 
                controller.salvar(nome, cpf, email, planoSelecionado);
                JOptionPane.showMessageDialog(this, "Torcedor salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else { 
                controller.atualizar(idTorcedorSelecionado, nome, cpf, email, planoSelecionado);
                JOptionPane.showMessageDialog(this, "Torcedor atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            }
            limparCampos();
            
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Erro de Validação: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (idTorcedorSelecionado == -1) {
               JOptionPane.showMessageDialog(this, "Selecione um torcedor na tabela para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
               return;
           }

           int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este torcedor?", "Confirmação", JOptionPane.YES_NO_OPTION);

           if (resposta == JOptionPane.YES_OPTION) {
               controller.excluir(idTorcedorSelecionado);
               limparCampos();
               JOptionPane.showMessageDialog(this, "Torcedor excluído com sucesso.");
           }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tabelaTorcedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTorcedoresMouseClicked
        int linha = tabelaTorcedores.getSelectedRow();
         if (linha != -1) {
            idTorcedorSelecionado = Integer.parseInt(String.valueOf(tabelaTorcedores.getValueAt(linha, 0)));
            String nome = (String) tabelaTorcedores.getValueAt(linha, 1);
            String cpf = (String) tabelaTorcedores.getValueAt(linha, 2);
            String email = (String) tabelaTorcedores.getValueAt(linha, 3);

            campoNomeTorcedor.setText(nome);
            campoCpf.setText(cpf);
            campoEmail.setText(email);

            String nomePlanoNaTabela = (String) tabelaTorcedores.getValueAt(linha, 4);
            DefaultComboBoxModel<Plano> model = (DefaultComboBoxModel<Plano>) comboPlanos.getModel();
            for (int i = 0; i < model.getSize(); i++) {
                if (model.getElementAt(i).getNome().equals(nomePlanoNaTabela)) {
                    comboPlanos.setSelectedIndex(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_tabelaTorcedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TorcedorView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNomeTorcedor;
    private javax.swing.JComboBox<Plano> comboPlanos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelPlanos;
    private javax.swing.JLabel labelTorcedor;
    private javax.swing.JTable tabelaTorcedores;
    // End of variables declaration//GEN-END:variables
}
